project_id = "xdxtcxseaymblvycryrn"

[functions.terminal]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.scheduled-backup]
verify_jwt = false

[functions.check-updates]
verify_jwt = false

[functions.totp]
verify_jwt = false
